apiVersion: v1
kind: Service
metadata:
  name: sample-catalog
  namespace: openapi
  labels:
    app: sample-catalog
    service: sample-catalog
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: sample-catalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-catalog
    service: sample-catalog
  name: sample-catalog
  namespace: openapi
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0%
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: sample-catalog
  template:
    metadata:
      labels:
        app: sample-catalog
    spec:
      containers:
      - image: asia.gcr.io/poc-innovation-iot/open-api/sample-catalog:2.0
        imagePullPolicy: Always
        name: sample-catalog
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 256M
          requests:
            cpu: 200m
            memory: 256M